jobs:
- template: .ci/build.yaml
  parameters:
    host: macOS
    pool:
      vmImage: 'macOS-10.13'

- template: .ci/build.yaml
  parameters:
    host: Linux
    pool:
      vmImage: 'Ubuntu-16.04'

- template: .ci/build.yaml
  parameters:
    host: Windows
    pool:
      vmImage: 'vs2017-win2016'
